postgresql: &postgresql
  adapter: postgresql
  encoding: utf8
  database: identity_reporting_rails_<%= Rails.env %>
  port: 5432
  username: <%= ENV['DOCKER_DB_USER'] %>

defaults: &defaults
  host: <%= ENV['DOCKER_DB_HOST'] || 'localhost' %>
  pool: 5
  <<: *postgresql
  # timeout settings
  timeout: <%= IdentityConfig.store.database_timeout %>
  reconnect: true
  connect_timeout: 2
  keepalives_idle: 10
  keepalives_interval: 10
  keepalives_count: 2
  checkout_timeout: 5
  reaping_frequency: 10
  variables:
    statement_timeout: <%= IdentityConfig.store.database_statement_timeout %>

development:
  primary:
    <<: *defaults
    adapter: postgis
    migrations_paths: db/primary_migrate
  read_replica:
    <<: *defaults
    adapter: postgis
    replica: true

test:
  primary: &test
    <<: *defaults
    adapter: postgis
    pool: 10
    checkout_timeout: 10
    database: <%= ENV['POSTGRES_DB'] || "identity_reporting_rails_test#{ENV['TEST_ENV_NUMBER']}" %>
    user: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    migrations_paths: db/primary_migrate
  read_replica:
    <<: *test
    adapter: postgis
    replica: true

production:
  primary:
    <<: *defaults
    adapter: postgis
    database: <%= IdentityConfig.store.database_name %>
    username: <%= IdentityConfig.store.database_username %>
    host: <%= IdentityConfig.store.database_socket.present? ?  IdentityConfig.store.database_socket : IdentityConfig.store.database_host %>
    password: <%= IdentityConfig.store.database_password %>
    pool: <%= primary_pool %>
    advisory_locks: <%= !IdentityConfig.store.database_socket.present? %>
    prepared_statements: <%= !IdentityConfig.store.database_socket.present? %>
    sslmode: <%= IdentityConfig.store.database_sslmode %>
    sslrootcert: '/usr/local/share/aws/rds-combined-ca-bundle.pem'
    migrations_paths: db/primary_migrate
  read_replica:
    <<: *defaults
    adapter: postgis
    database: <%= IdentityConfig.store.database_name %>
    username: <%= IdentityConfig.store.database_readonly_username %>
    host: <%= IdentityConfig.store.database_read_replica_host %>
    password: <%= IdentityConfig.store.database_readonly_password %>
    pool: <%= primary_pool %>
    sslmode: <%= IdentityConfig.store.database_sslmode %>
    sslrootcert: '/usr/local/share/aws/rds-combined-ca-bundle.pem'
    replica: true
