postgresql: &postgresql
  adapter: postgresql
  encoding: utf8
  database: identity_reporting_rails_<%= Rails.env %>
  port: 5432

defaults: &defaults
  host: <%= ENV['DOCKER_DB_HOST'] || 'localhost' %>
  pool: 5
  <<: *postgresql
  # timeout settings
  timeout: <%= Identity::Hostdata.config.database_timeout %>
  reconnect: true
  connect_timeout: 2
  keepalives_idle: 10
  keepalives_interval: 10
  keepalives_count: 2
  checkout_timeout: 5
  reaping_frequency: 10
  variables:
    statement_timeout: <%= Identity::Hostdata.config.database_statement_timeout %>

development:
  primary:
    <<: *defaults
    adapter: postgresql
    migrations_paths: db/primary_migrate
  read_replica:
    <<: *defaults
    adapter: postgresql
    replica: true
  worker_jobs:
    <<: *defaults
    database: identity_reporting_rails_worker_jobs_<%= Rails.env %>
    migrations_paths: db/worker_jobs_migrate
  data_warehouse:
    <<: *defaults
    database: identity_reporting_rails_data_warehouse_<%= Rails.env %>
    schema_search_path: 'logs,public'
    migrations_paths: db/data_warehouse_migrate

test:
  primary: &test
    <<: *defaults
    adapter: postgresql
    pool: 10
    checkout_timeout: 10
    database: <%= ENV['POSTGRES_DB'] || "identity_reporting_rails_test#{ENV['TEST_ENV_NUMBER']}" %>
    user: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    migrations_paths: db/primary_migrate
  read_replica:
    <<: *test
    adapter: postgresql
    replica: true
  worker_jobs:
    <<: *test
    database: <%= "identity_reporting_rails_test#{ENV['TEST_ENV_NUMBER']}" %>
    migrations_paths: db/worker_jobs_migrate
  data_warehouse:
    <<: *test
    database: <%= "identity_reporting_rails_test#{ENV['TEST_ENV_NUMBER']}" %>
    migrations_paths:
      - db/data_warehouse_migrate
      - db/data_warehouse_test_migrate

<%
  worker_pool = if Identity::Hostdata.instance_role == 'worker'
    GoodJobConnectionPoolSize.calculate_worker_pool_size(
      queues: Identity::Hostdata.config.good_job_queues,
      cron_enabled: true,
      max_threads: Identity::Hostdata.config.good_job_max_threads,
    )
  else
    Identity::Hostdata.config.database_pool_reporting
  end
%>

<%
  primary_pool = if Identity::Hostdata.instance_role == 'worker'
    GoodJobConnectionPoolSize.calculate_primary_pool_size(
      queues: Identity::Hostdata.config.good_job_queues,
      max_threads: Identity::Hostdata.config.good_job_max_threads,
    )
  else
    Identity::Hostdata.config.database_pool_reporting
  end
%>

production:
  primary:
    <<: *defaults
    adapter: postgresql
    database: <%= Identity::Hostdata.config.database_name %>
    username: <%= Identity::Hostdata.config.database_username %>
    host: <%= Identity::Hostdata.config.database_socket.present? ?  Identity::Hostdata.config.database_socket : Identity::Hostdata.config.database_host %>
    password: <%= Identity::Hostdata.config.database_password %>
    pool: <%= primary_pool %>
    advisory_locks: <%= !Identity::Hostdata.config.database_socket.present? %>
    prepared_statements: <%= !Identity::Hostdata.config.database_socket.present? %>
    sslmode: <%= Identity::Hostdata.config.database_sslmode %>
    sslrootcert: '/usr/local/share/aws/rds-combined-ca-bundle.pem'
    migrations_paths: db/primary_migrate
  read_replica:
    <<: *defaults
    adapter: postgresql
    database: <%= Identity::Hostdata.config.database_name %>
    username: <%= Identity::Hostdata.config.database_readonly_username %>
    host: <%= Identity::Hostdata.config.database_read_replica_host %>
    password: <%= Identity::Hostdata.config.database_readonly_password %>
    pool: <%= primary_pool %>
    sslmode: <%= Identity::Hostdata.config.database_sslmode %>
    sslrootcert: '/usr/local/share/aws/rds-combined-ca-bundle.pem'
    replica: true
  worker_jobs:
    <<: *defaults
    database: <%= Identity::Hostdata.config.database_worker_jobs_name %>
    username: <%= Identity::Hostdata.config.database_worker_jobs_username %>
    host: <%= Identity::Hostdata.config.database_worker_jobs_host %>
    password: <%= Identity::Hostdata.config.database_worker_jobs_password %>
    pool: <%= worker_pool %>
    sslmode: <%= Identity::Hostdata.config.database_worker_jobs_sslmode %>
    sslrootcert: '/usr/local/share/aws/rds-combined-ca-bundle.pem'
    migrations_paths: db/worker_jobs_migrate
  data_warehouse:
    adapter: redshift
    host: <%= URI.parse("redshift://#{Identity::Hostdata.config.redshift_host}").host %>
    port: 5439
    database: <%= Identity::Hostdata.config.redshift_database_name %>
    username: <%= Identity::Hostdata.config.redshift_username %>
    password: <%= Identity::Hostdata.config.redshift_password %>
    encoding: utf8
    migrations_paths: db/data_warehouse_migrate
